### PR TITLE
Added "get favorite tweets" functionality

### PR DESCRIPTION
**Pull request by joshfermin**
# Get Favorites
- Implemented functionality to get the top 20 most recently favorited tweets from a given user.
- To run:

```
> ruby get_favorites.rb -p oauth.properties "<screen_name>"
```
- This will return a json file containing all the data for the top 20 favorited tweets by that person.

### CODE REVIEW

**Comment by kenbod** [comment]
Hi Josh,

This is a great start but take a look at the documentation. This is an endpoint that makes use of the max_id parameter to traverse the entire timeline of a user's favorited tweets. I'd like to challenge you to see if you can subclass MaxIdRequest instead so that your app can get all of a user's favorite tweets.

Let me know if you have questions. Thanks!

**Comment by joshfermin** [comment]
@kenbod I implemented the subclass MaxIdRequest instead of the Twitter Request, but I limited it to get only the top 100 favorited tweets from a user. This was because I was getting things like:

```
Response Code: 429
Response Info: Too Many Requests
```

And also really long sleep times.

**Comment by kenbod** [comment]
Weird that you're getting the 429 errors. The framework should still keep track of the number of requests you are allowed to make and not go past that limit. Anyway, this request should be implemented in the same way that Search.rb was implemented and not the way that Timeline was implemented. You don't necessarily want to make 5 requests or 16 requests, you want to loop until all favorited tweets are collected. Unlike Search.rb we can ask for 200 tweets per request, so we want to bump the params[:count] parameter from 100 to 200 and then we want to loop until zero tweets are returned, which is what the logic in Search.rb does.

I mocked out a quick implementation and ran it and it made 15 requests for 200 favorite tweets each and ended up with 2973 tweets before it had to go to sleep due to rate limits. I'm going to let it run in the background while I work to see how it long it takes to download all of my favorited tweets.

So, switch your  implementation of Favorites.rb to mimic Search.rb rather than Timeline.rb and you should see better results.

**Comment by joshfermin** [comment]
@kenbod I think I finally got it!

**Comment by kenbod** [comment]
I agree. Good work!

**Pull request merged**
