### PR TITLE
Get recent mentions of authenticating user - Edward Zhu

### PR DESCRIPTION
**Pull request by zhued**
This will add functionality to get most recent mentions (tweets containing a users’s @screen_name) for the authenticating user.

Usage:

```
ruby PATH/get_mentions.rb <options> <trim_user>
```

`<options>`: The path of your OAuth credentials file
`<trim_user>`: To trim the mention tweets or not. Setting true, t or 1, will return a timeline with user objects including only the status authors numerical ID.

Examples to test it out:

ruby apps/get_mentions.rb -p oauth.properties true 
ruby apps/get_mentions.rb -p oauth.properties false

### CODE REVIEW

**Comment by kenbod** [comment]
Hi Edward. This is a great start but try basing your code off of the Search.rb request rather than the Timeline.rb request. This method can return potentially 800 tweets maximum but you need to loop until the tweet count returned for a request is zero tweets rather than looping a total of 16 times. Looping 16 times was specific to the Timeline.rb request since it can receive a maximum of 3200 tweets. If you switch your MentionsTimeline.rb class to mimic Search.rb, I think it will be able to retrieve the maximum of 800 tweets across 4 to 5 requests easy. (Of course, it will be hard to test that since we would need to find a user who has been mentioned at least 800 times!)

**Comment by zhued** [comment]
@kenbod I have successfully changed MentionsTimeline.rb to mimic Search.rb. Thanks for explaining it in such a concise way, I definitely understand why the change is necessary now!

**Comment by kenbod** [comment]
Okay, looks good. Thank you!

**Comment by kenbod** [comment]
I just used your app to discover that I've been mentioned on Twitter 552 times! :smiley:

**Comment by kenbod** [comment]
I just pushed a commit where I did some tweaks to your files. I updated the code to use Trollop to handle the 'trim_user' parameter and I modified MentionsTimeline to make use of the include_param? mechanism to determine if trim_user should be included in the outgoing request. Check it out if interested!

**Pull request merged**
