### PR TITLE
Sabnis upendra

### PR DESCRIPTION
**Pull request by upensabnis**
Implemented twitter geo/search api. Added 2 files:
1. apps/geo_search.rb
2. requests/SearchGeo.rb

### CODE REVIEW

**Comment by upensabnis** [comment]
Implemented twitter geo/search api. Added 2 files:
1. apps/geo_search.rb
2. requests/SearchGeo.rb

**Comment by kenbod** [comment]
Hey, you weren't supposed to merge your own pull request! That's my job!

I need to review your code before I pull it in to make it an official part of the repository.

**Comment by upensabnis** [comment]
Ahh sorry. I mistakenly merged the branch while creating a pull request. I will try to revert the merge.

**Comment by kenbod** [comment]
Okay, thank you. I merged in the "revert". Now, go back to your forked repository and make sure everything is in order and then create a new pull request. I'll be reviewing pull requests tomorrow before class. Thanks!

**Pull request merged**
