### PR TITLE
Added UsersProfileBanner.rb and get_profile_banner.rb

### PR DESCRIPTION
**Pull request by Kevin-Rau**

### CODE REVIEW

**Comment by Kevin-Rau** [comment]
Added UsersProfileBanner.rb and get_profile_banner.rb to Twitter Framework to receive profile banner information from a given user.

**Comment by kenbod** [comment]
Hi. You have your application set-up to send a list of user ids or a list of screen names to this endpoint. But, [according to the documentation](https://dev.twitter.com/rest/reference/get/users/profile_banner), this endpoint expects just a single screen name or user name. Would you fix the application file so that you can only submit a single value for screen name or user name?

**Comment by kenbod** [comment]
Why did you merge your changes into the official framework? That's my job, not yours! I haven't had a chance to review your code! I'm going to revert the change. Then, I want you to add the commit to your forked repository, not the official repository. That should then add the commit to your pull request.

**Comment by Kevin-Rau** [comment]
I am sorry it merged, I thought it was just adding to the commit. I am still getting the hang of working around github. I think I added a new commit to my repository so it will show to my pull request. Sorry again for the mess up.

**Pull request merged**
